metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  name: VOCDataSet
  dataset_dir: C:/Users/susususu/Desktop/paddle/ppq/dataset/train
  anno_path: train_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: C:/Users/susususu/Desktop/paddle/ppq/dataset/val
  anno_path: val_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: C:/Users/susususu/Desktop/paddle/ppq/dataset/train/label_list.json